export const config = {
    BOT_TOKEN_API: process.env.BOT_TOKEN_API || '',

    MONGODB_URL: process.env.MONGODB_URL || '',

    PORT: process.env.PORT || 5001,

    ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS || '',

    CRON_JOB_NOTIFICATION_PERIOD: process.env.CRON_JOB_NOTIFICATION_PERIOD || '',

    CRYPTO_POSITIVE_BORDERS_NOTIFICATION: process.env.CRYPTO_POSITIVE_BORDERS_NOTIFICATION || '',
    CRYPTO_NEGATIVE_BORDERS_NOTIFICATION: process.env.CRYPTO_NEGATIVE_BORDERS_NOTIFICATION || ''
};
